name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup pnpm and Node.js
      uses: pnpm/setup@v1
      with:
        runtime: node@24
        cache: true

    - name: Install and Build
      run: |
        pnpm install --frozen-lockfile
        pnpm run build

    - name: Lint and Test
      run: |
        pnpm run lint
        pnpm run test
